#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.12 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfffd;
constexpr uint24_t FX_DATA_BYTES = 674;

constexpr uint24_t ArduboyLogo = 0x000000;
constexpr uint16_t ArduboyLogoWidth  = 88;
constexpr uint16_t ArduboyLogoHeight = 16;

constexpr uint24_t FXLogo = 0x0000B4;
constexpr uint16_t FXLogoWidth  = 28;
constexpr uint16_t FXLogoHeight = 16;

constexpr uint24_t ArduboyLogo_Frame = 0x000128;
constexpr uint24_t ArduboyLogo_LastFrame = 0x000290;
