#pragma once

/**** FX data header generated by fx-data.py tool version 1.00 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfffe;
constexpr uint24_t FX_DATA_BYTES = 392;

constexpr uint24_t FX_DATA_TILES = 0x000000;
constexpr uint24_t FX_DATA_TILEMAP = 0x000044;
constexpr uint24_t FX_DATA_BALLS = 0x000144;
