#pragma once

/**** FX data header generated by fx-data.py tool version 1.00 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff65;
constexpr uint24_t FX_DATA_BYTES = 39470;

constexpr uint24_t mapGfx = 0x000000;
constexpr uint24_t whaleGfx = 0x0092A4;
